# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('is_correct', models.BooleanField()),
            ],
        ),
    ]
