# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-16 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invgatechallenge', '0002_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='used',
        ),
    ]
