# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invgatechallenge', '0003_remove_token_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
            ],
        ),
    ]
