# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invgatechallenge', '0004_hackdetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lastname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='token',
            name='uniqid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
